/**
 * weather_icons.h — LVGL image declarations for Meteocons weather icons
 *
 * Icons by Bas Milius (MIT License) — https://bas.dev
 * https://github.com/basmilius/weather-icons
 *
 * Each icon_xxx.c file is generated by the LVGL v8 Online Image Converter:
 * https://lvgl.io/tools/imageconverter
 * Settings: LVGL v8, CF_TRUE_COLOR, C array output
 *
 * Icon size: 64×64 pixels
 */

#ifndef WEATHER_ICONS_H
#define WEATHER_ICONS_H

#include <lvgl.h>

#define WEATHER_ICON_W 64
#define WEATHER_ICON_H 64

/* Declare all icon images (defined in their individual .c files) */
LV_IMG_DECLARE(icon_clear_day);
LV_IMG_DECLARE(icon_clear_night);
LV_IMG_DECLARE(icon_partly_cloudy_day);
LV_IMG_DECLARE(icon_partly_cloudy_night);
LV_IMG_DECLARE(icon_overcast);
LV_IMG_DECLARE(icon_fog);
LV_IMG_DECLARE(icon_drizzle);
LV_IMG_DECLARE(icon_rain);
LV_IMG_DECLARE(icon_heavy_rain);
LV_IMG_DECLARE(icon_freezing_rain);
LV_IMG_DECLARE(icon_snow);
LV_IMG_DECLARE(icon_thunderstorm);
LV_IMG_DECLARE(icon_unknown);

/**
 * Get the appropriate icon for a WMO weather code.
 * is_day: true = daytime, false = nighttime (from Open-Meteo "is_day" field)
 */
static inline const lv_img_dsc_t* get_weather_icon(int wmo_code, bool is_day) {
  switch (wmo_code) {
    case 0:  /* Clear sky */
    case 1:  /* Mainly clear */
      return is_day ? &icon_clear_day : &icon_clear_night;

    case 2:  /* Partly cloudy */
      return is_day ? &icon_partly_cloudy_day : &icon_partly_cloudy_night;

    case 3:  /* Overcast */
      return &icon_overcast;

    case 45: /* Fog */
    case 48: /* Depositing rime fog */
      return &icon_fog;

    case 51: /* Light drizzle */
    case 53: /* Moderate drizzle */
    case 55: /* Dense drizzle */
      return &icon_drizzle;

    case 56: /* Light freezing drizzle */
    case 57: /* Dense freezing drizzle */
    case 66: /* Light freezing rain */
    case 67: /* Heavy freezing rain */
      return &icon_freezing_rain;

    case 61: /* Slight rain */
    case 63: /* Moderate rain */
    case 80: /* Slight rain showers */
    case 81: /* Moderate rain showers */
      return &icon_rain;

    case 65: /* Heavy rain */
    case 82: /* Violent rain showers */
      return &icon_heavy_rain;

    case 71: /* Slight snow */
    case 73: /* Moderate snow */
    case 75: /* Heavy snow */
    case 77: /* Snow grains */
    case 85: /* Slight snow showers */
    case 86: /* Heavy snow showers */
      return &icon_snow;

    case 95: /* Thunderstorm */
    case 96: /* Thunderstorm with slight hail */
    case 99: /* Thunderstorm with heavy hail */
      return &icon_thunderstorm;

    default:
      return &icon_unknown;
  }
}

#endif /* WEATHER_ICONS_H */
